### ISSUE TITLE
Can I use this within our GHE instance?

### ISSUE THREAD

**Issue by richnsoos** [Jimdo/github-sync-labels-milestones#11]
When I try to use this tool to add labels and a milestone to a repo that lives within an org in our Enterprise GH instance, I get 

```
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

I'm using a personal token that I generated for my GHE user account. 

Alternatively, tool worked as expected and successfully created labels and a milestone for a repo in my public GH user org so it's set up correctly. Can this tool be used to add labels / milestone to a repo in an org in GHE? I'm an owner of that org.

Thanks!

**Comment by Xiphe** [comment]
Hey @richnsoos 

currently this is not supported but that should be fairly easy.

Under the hood, this project uses [the github package from npm](https://www.npmjs.com/package/github) which supports a custom `host` and `pathPrefix` for GHE.

I'd just pass these parameters through from cli if present.
I might be able to do that tomorrow, but cant promise that. Feel free to open a PR if you're faster ;)

**Comment by Xiphe** [comment]
I added support to set `host` and `path-prefix` could you please test if that works for you?

**Comment by richnsoos** [comment]
yes, i will test today! thank you

**Comment by richnsoos** [comment]
Yes, it works great to create labels and milestones in repos in our GHE instance! Thank you~~!
