### ISSUE TITLE
Question: Is it possible to get additional error details?

### ISSUE THREAD

**Issue by richnsoos** [Jimdo/github-sync-labels-milestones#12]
I'm encountering an issue when running this command:

```
github-sync-labels-milestones -t [my personal access token] -c config.json --host github.[ourenterpriseinstance].com --path-prefix /api/v3
```

and getting this error:

```
{"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.8/v3"}
```

I've confirmed my github-sync-labels-milestones installation is good by successfully updating labels in one of my repos in my public github user account, using the same command, but with my personal access token for my public github user account.

The last time I successfully updated labels in one of our repos in our enterprise GH instance using this awesome tool was 1/23.

**Questions**:
- is there any reason the tool would stop working as expected for GHEs between then and now?
- is there any way that I can generate more error details? for example, what specifically is "not found"?

I've confirmed our GHE is version 2.8 and that `https://github.[ourenterpriseinstance].com/api/v3/repos/[ourorg]/[ourrepo]/labels` (for example) is a good endpoint that returns json, confirming the correct path prefix.

Thanks again for sharing any insights you can share.

**Comment by Xiphe** [comment]
This error is the exact response from your GitHub installation, I'm afraid there is not much more information besides maybe the request that got the response (happy to see a PR if you want to contrib. more verbose logging).

That said, I stumbled upon "Not Found" errors when the (bot)-user has no write access to a repo.
Maybe s.o. removed your user from a team or you added a new repo and have not granted access to the user.

**Comment by richnsoos** [comment]
@Xiphe  You are absolutely right. I was unaware that I was trying to update labels for a repo to which I have no write access. After ensuring I had write access to the repo, it worked. Thanks!!
