### ISSUE TITLE
github-sync-labels-milestones broken?

### ISSUE THREAD

**Issue by hredestig** [Jimdo/github-sync-labels-milestones#13]
This was such an extremely useful tool but since a few days I now only get

```
➜  scrum git:(master) ✗ github-sync-labels-milestones -t $GH_TOKEN -c config.json
{"message": "We had issues producing the response to your request. Sorry about that. Please try resubmitting your request and contact us if the problem persists."}
```

Am I the only person to experience this?

**Comment by hredestig** [comment]
Oops, just my bad (had renamed a repository and that doesn't sit well with github-sync-labels-milestones), thanks anyway!

**Comment by Xiphe** [comment]
glad you could solve your prob 🎉
