### ISSUE TITLE
Can't update label description

### ISSUE THREAD

**Issue by tkrempser** [Jimdo/github-sync-labels-milestones#18]
Is there any way to update the label description?

**Comment by Xiphe** [comment]
Currently no, when I wrote this, there were not label descriptions. But I agree that this would be a good addition.

**Comment by pbochynski** [comment]
I had to solve the same problem for my repositories and I created a similar tool. It manages label descriptions and colors (but no auto renaming). You can check it here: https://github.com/pbochynski/github-sync

**Comment by Xiphe** [comment]
should work with v0.4.2
