### ISSUE TITLE
[Security] Token in HTTP header instead of query param

### ISSUE THREAD

**Issue by josemore** [Jimdo/github-sync-labels-milestones#19]
Did a quick test to sync my labels using this tool. 
I got a warning from Github:
"Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation."

**Comment by Xiphe** [comment]
Thanks for reporting.
I currently don't have the time to work on this tool but PRs are very welcome.

**Comment by RonenYAtZenity** [comment]
It is not a warning anymore:
{"message":"Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param","documentation_url":"https://docs.github.com/v3/#oauth2-token-sent-in-a-header"}
I guess that till fixed we will not be able to use the tool?

**Comment by Xiphe** [comment]
I'll try to fix this soon™

**Comment by Xiphe** [comment]
version 0.4.2 should work again. could you please check?
