### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by seiffert** [Jimdo/github-sync-labels-milestones#2]
I'm getting a strange error...

``` bash
$ nodejs node_modules/github-sync-labels-milestones/cli.js -t <token> -c github_sync_config.json -v 
{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
undefined
```

My `github_sync_config.json`:

``` json
[{
  "repositories": [
    [...] // a lot of private repositories to which the github token has access
  ],
  "milestones": [{
    "title": "Test Milestone",
    "state": "open",
    "description": "Just a test",
    "due_on": "2015-10-31T23:59:59Z"
  }],
  "labels": [
      { "name": "bug", "color": "fc2929" },
      { "name": "duplicate", "color": "cccccc" },
      { "name": "enhancement", "color": "84b6eb" },
      { "name": "help wanted", "color": "159818" },
      { "name": "invalid", "color": "e6e6e6" }, 
      { "name": "question", "color": "cc317c" }, 
      { "name": "wontfix", "color": "ffffff" }, 
      { "name": "in progress", "color": "ededed" }, 
      { "name": "ready", "color": "ededed" }, 
      { "name": "feature-request", "color": "fbca04" }, 
      { "name": "via-chat", "color": "ededed" }, 
      { "name": "review", "color": "ededed" }, 
      { "name": "easy-pick", "color": "d7e102" } 
  ]
}]
```

Can you help me to debug this issue? Thanks!

**Comment by seiffert** [comment]
Ok, I think I found it. The issue was that the token was generated for a member of a team that didn't had write access to all repositories in the list.

Maybe you could mention this as a requirement in the README.
Also it's quite hard to debug such errors, I had to put some log statements into the `lib/updateLabels.js` script myself ;-)

**Comment by Xiphe** [comment]
I guess "Not found" hints that it could be something with access rights, but it surely would help if the error would be more communicative about what exactly could not be found ;)

I agree that we can be more explicit about the user/token requirements.

**Comment by Xiphe** [comment]
since I don't have the time to fully maintain this tool, I'll apply a rule-of-three here and come up with s.th. once this happens a few more times.
