### ISSUE TITLE
Show which repository caused an error

### ISSUE THREAD

**Issue by ysndr** [Jimdo/github-sync-labels-milestones#20]
I recently had to go through every updated repository to find out which one did not grant my token enough access rights to write the milestone.
It would be great if this was included in the error message instead of

```
HttpError: Not Found
HttpError: Not Found
```

**Comment by Xiphe** [comment]
Sounds reasonable. Sorry for the inconvenience and thanks for the feedback!

**Comment by Xiphe** [comment]
fixed with [`v0.4.3`](https://github.com/Xiphe/github-sync-labels-milestones/releases/tag/v0.4.3)

**Comment by ysndr** [comment]
Danke!
