### ISSUE TITLE
add support cson or yaml

### ISSUE THREAD

**Issue by OleMchls** [Jimdo/github-sync-labels-milestones#3]
I broke my keyboard on the 1000th `{` stroke :crying_cat_face:

**Comment by Xiphe** [comment]
PR's are welcome :P

**Comment by SpainTrain** [comment]
We've been using yaml for syncing without first class support.  I created an example project based on our use at https://github.com/homezen/gslm-starter-project

**Comment by Xiphe** [comment]
great thing!
from what i see, [yaml to json is converted here](https://github.com/homezen/gslm-starter-project/blob/bf6c0934b9979191ce706811728079b907eefd1b/package.json#L8)

**Comment by SpainTrain** [comment]
Yup, we tend to use "canonical" cli apps when possible. If I had the js at hand for conversion I def would have opened a pr 😉

Great project btw. Has helped us a **ton**
