### ISSUE TITLE
ownership

### ISSUE THREAD

**Issue by Xiphe** [Jimdo/github-sync-labels-milestones#9]
@p0wl could you redirect this if needed?

I don't have write access to this anymore and in the past i've been the only active maintainer. Is there s.o. taking over the ownership? If not be welcome to hand this project over to `Xiphe/github-sync-labels-milestones`

**Comment by p0wl** [comment]
I'll take care.

**Comment by sbstjn** [comment]
![screen shot 2016-11-14 at 11 24 27](https://cloud.githubusercontent.com/assets/248965/20261160/f338de2e-aa5c-11e6-9784-32de8866946c.png)

**Comment by sbstjn** [comment]
I have added you as an `admin` collaborator. Please try to transfer the ownership to your account …

**Comment by Xiphe** [comment]
No settings Tab visible for me :( ~~but at least i can merge now :)~~

nope, can't merge... sure the rights were correct?

**Comment by Xiphe** [comment]
Nevermind, i had to accept the invitation first...
